/*
 * APIMATICCalculator.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/02/2016
 */
using APIMATICCalculator.PCL.Http.Client;
using APIMATICCalculator.PCL.Http.Request;
using APIMATICCalculator.PCL.Http.Response;

namespace APIMATICCalculator.Tests.Helpers
{
    public class HttpCallBackEventsHandler
    {
        public HttpRequest Request { get; private set; }

        public HttpResponse Response { get; private set; }

        public void OnBeforeHttpRequestEventHandler(IHttpClient source, HttpRequest request)
        {
            this.Request = request;
        }

        public void OnAfterHttpResponseEventHandler(IHttpClient source, HttpResponse response)
        {
            this.Response = response;
        }
    }
}
